### ISSUE TITLE
Namespace Gimp not available

### ISSUE THREAD

**Issue by xXPerditorXx** [UserUnknownFactor/GIMP3-ML#5]
**Describe the bug**
If I download the plugins folder and add it to thr gimp plugin path I get the Error below.

**To Reproduce**
`git clone https://github.com/UserUnknownFactor/GIMP3-ML.git` and add the 'plugins' folder to gimp plugins

![image](https://github.com/UserUnknownFactor/GIMP3-ML/assets/60017046/9b18f813-bbd1-4879-aab7-57065dac7643)

**Python Error**
```
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/superresolution/superresolution.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/semseg/semseg.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/plugin_utils.py", line 1, in <module>
    import gi
ImportError: No module named gi
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/monodepth/monodepth.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/matting/matting.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/kmeans/kmeans.py", line 16, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/interpolation/interpolation.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/inpainting/inpainting.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/filterfolder/filterfolder.py", line 18, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/faceparse/faceparse.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/enlighten/enlighten.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/detectobjects/detectobjects.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/denoise/denoise.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/dehaze/dehaze.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/deblur/deblur.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/colorpalette/colorpalette.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/coloring/coloring.py", line 17, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/xxperditorxx/.var/app/org.gimp.GIMP/config/GIMP/2.10/plug-ins/canny/canny.py", line 16, in <module>
    gi.require_version("Gimp", "3.0")
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gimp not available
gimp-2.10: LibGimpBase-WARNING: gimp-2.10: gimp_wire_read(): error
```

**Desktop (please complete the following information):**
 - OS Version: Arch Linux 6.3.5 KDE Plasma 5.27.5
 - GIMP Version: 2.10.34

**Comment by xXPerditorXx** [comment]
The same problem also exists in the original GIMP-ML.

**Comment by UserUnknownFactor** [comment]
You need the **development** version of GIMP not the release one. Its version should be `2.99.14`, and not `2.10`...
